name: Docker Image CI

on:
  push:
    branches:
      - 7.1.33
    paths:
      - '**/Dockerfile'
      - '**/*.sh'
      - '**/*.conf'
      - '**/*.ini'
      - 'docker-entrypoint.sh'
      - 'index.php'
  pull_request:
    branches:
      - 7.1.33
    paths:
      - '**/Dockerfile'
      - '**/*.sh'
      - '**/*.conf'
      - '**/*.ini'
      - 'docker-entrypoint.sh'
      - 'index.php'

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - 7.1.33-fpm-alpine3.10
          - 7.2.34-fpm-alpine3.12
          - 7.4.30-fpm-alpine3.16
          - 8.1.7-fpm-alpine3.16

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./${{ matrix.version }}/Dockerfile
          push: true
          tags: nekoimi/rafutaria-php:${{ matrix.version }}
